{% set name = "river-cpp" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pbotros/river/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c3e7cddfdb220f921fad61cad54eedc20ee4be2e12ceca2ddfd8cf407790bfa7

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("river-cpp", max_pin="x.x") }}

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - glog
  run:
    - gflags
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  commands:
    - test -d ${PREFIX}/include/river  # [unix]
    - test -f ${PREFIX}/include/river/river.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/river/river-config.cmake  # [unix]
    - test -f ${PREFIX}/lib/libriver.so  # [linux]
    - test -f ${PREFIX}/lib/libriver.dylib  # [osx]
    - if exist %LIBRARY_PREFIX%\include\river\river.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\river-config.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\bin\river.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/pbotros/river
  summary: 'High-throughput, structured, and persistent streaming'
  description: |
    A high-throughput, structured streaming framework built atop Redis Streams, with optional support for persistence-to-disk. C++ and Python support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pbotros
