{% set name = "river-cpp" %}
{% set version = "1.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pbotros/river/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 04f6712d220a97fde76e3ed5998832c4a7ba790137cf656f8c2d1290077b8eaf

build:
  number: 6
  run_exports:
    - {{ pin_subpackage("river-cpp", max_pin="x.x") }}

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake <4
    - make  # [not win]
    - ninja  # [win]
    - pkg-config
    - zfp  # [not osx or not arm64]
  host:
    - spdlog
  run:
    - spdlog
    - zfp

test:
  commands:
    - test -d ${PREFIX}/include/river  # [unix]
    - test -f ${PREFIX}/include/river/river.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/river/river-config.cmake  # [unix]
    - test -f ${PREFIX}/lib/libriver.so  # [linux]
    - test -f ${PREFIX}/lib/libriver.dylib  # [osx]
    - if exist %LIBRARY_PREFIX%\include\river\river.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\river-config.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\bin\river.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/pbotros/river
  summary: High-throughput, structured, and persistent streaming
  description: |
    A high-throughput, structured streaming framework built atop Redis Streams, with optional support for persistence-to-disk. C++ and Python support.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pbotros
